### ISSUE TITLE
Fork link error

### ISSUE THREAD

**Issue by Juliag875** [learn-co-curriculum/phase-1-control-flow-lab#3]
### Canvas Link

https://learning.flatironschool.com/courses/4985/assignments/163563?module_item_id=351890

### Concern

Fork button at my Canvas account does not link me to GitHub account

### Additional Context

Fork button at my Canvas account does not link me to GitHub account

**Comment by graciemcguire** [comment]
Hello! Thanks for submitting this issue.
The fork link may not have been working because of a server error, and isn't something we can change on our end. (This is likely why the GitHub link was still working! 😄) 
I'm going to go ahead and close this issue, but if you think I've closed the issue in error please reopen and we will take another look!
